/**
 * AI Character Generator — creates vivid governance character profiles
 * for DReps and SPOs using their on-chain behavior data.
 *
 * Characters are generated by Seneca (the platform's AI persona) and
 * cached per-epoch. Input hashing detects when re-generation is needed.
 */

import { createHash } from 'crypto';
import { buildSenecaPrompt } from '@/lib/ai/senecaPersona';
import { generateJSON } from '@/lib/ai';
import { logger } from '@/lib/logger';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CharacterInput {
  entityId: string;
  name: string | null;
  alignments: {
    treasuryConservative: number;
    treasuryGrowth: number;
    decentralization: number;
    security: number;
    innovation: number;
    transparency: number;
  };
  votePattern: {
    total: number;
    yesRate: number;
    abstainRate: number;
    proposalTypesVoted: string[];
  };
  scoreComponents: {
    engagementQuality: number;
    effectiveParticipation: number;
    reliability: number;
    governanceIdentity: number;
    semanticDiversity: number;
  };
  rationaleQuality: 'none' | 'minimal' | 'substantive' | 'excellent';
  delegatorTrend: 'growing' | 'stable' | 'declining';
  delegatorCount: number;
  profileText: string | null;
  tier: string;
  ccAlignment: number | null;
}

export interface CharacterOutput {
  title: string;
  summary: string;
  pills: Array<{ label: string; reason: string }>;
}

// ---------------------------------------------------------------------------
// Emerging Voice fallback
// ---------------------------------------------------------------------------

const EMERGING_VOICE_CHARACTER: CharacterOutput = {
  title: 'Emerging Voice',
  summary:
    'This representative has recently entered governance. A few more votes will reveal their character.',
  pills: [
    { label: 'New arrival', reason: 'Fewer than 3 governance votes on record' },
    { label: 'Character forming', reason: 'Voting patterns not yet established' },
    { label: 'Watch this space', reason: 'Character will emerge with more activity' },
  ],
};

/**
 * Returns the static "Emerging Voice" fallback for entities that lack
 * sufficient voting history (< 3 votes) to generate a meaningful character.
 */
export function getEmergingVoiceCharacter(_epoch: number): CharacterOutput {
  return EMERGING_VOICE_CHARACTER;
}

// ---------------------------------------------------------------------------
// Input hashing
// ---------------------------------------------------------------------------

/**
 * Compute a stable SHA-256 hash of the character input.
 * Used to detect when an entity's governance profile has changed enough
 * to warrant re-generating the character.
 */
export function computeInputHash(input: CharacterInput): string {
  const json = JSON.stringify(input);
  return createHash('sha256').update(json).digest('hex');
}

// ---------------------------------------------------------------------------
// Character generation
// ---------------------------------------------------------------------------

function buildEntityDescription(input: CharacterInput, entityType: 'drep' | 'spo'): string {
  const entityLabel = entityType === 'drep' ? 'DRep' : 'Stake Pool Operator';
  const { alignments, votePattern, scoreComponents, rationaleQuality, delegatorTrend } = input;

  const parts: string[] = [
    `This ${entityLabel} is currently in the "${input.tier}" tier with ${input.delegatorCount} delegators (trend: ${delegatorTrend}).`,
    '',
    `VOTING RECORD:`,
    `- ${votePattern.total} total votes, ${Math.round(votePattern.yesRate * 100)}% yes, ${Math.round(votePattern.abstainRate * 100)}% abstain`,
    `- Proposal types voted on: ${votePattern.proposalTypesVoted.length > 0 ? votePattern.proposalTypesVoted.join(', ') : 'mixed'}`,
    `- Rationale quality: ${rationaleQuality}`,
    '',
    `GOVERNANCE ALIGNMENT (0-100):`,
    `- Treasury conservative: ${Math.round(alignments.treasuryConservative)}`,
    `- Treasury growth: ${Math.round(alignments.treasuryGrowth)}`,
    `- Decentralization: ${Math.round(alignments.decentralization)}`,
    `- Security: ${Math.round(alignments.security)}`,
    `- Innovation: ${Math.round(alignments.innovation)}`,
    `- Transparency: ${Math.round(alignments.transparency)}`,
    '',
    `SCORE BREAKDOWN (0-100):`,
    `- Engagement quality: ${Math.round(scoreComponents.engagementQuality)}`,
    `- Effective participation: ${Math.round(scoreComponents.effectiveParticipation)}`,
    `- Reliability: ${Math.round(scoreComponents.reliability)}`,
    `- Governance identity: ${Math.round(scoreComponents.governanceIdentity)}`,
    `- Semantic diversity: ${Math.round(scoreComponents.semanticDiversity)}`,
  ];

  if (input.ccAlignment !== null) {
    parts.push(`- Constitutional Committee alignment: ${Math.round(input.ccAlignment)}%`);
  }

  if (input.profileText) {
    parts.push('', `SELF-DESCRIPTION: "${input.profileText.slice(0, 300)}"`);
  }

  if (input.name) {
    parts.push('', `DISPLAY NAME: ${input.name}`);
  }

  return parts.join('\n');
}

/**
 * Generate an AI character profile for a DRep or SPO.
 *
 * Uses Seneca's voice with the entity-specific context to produce
 * a memorable title, summary, and attribute pills grounded in
 * observable governance behavior.
 */
export async function generateCharacter(
  input: CharacterInput,
  entityType: 'drep' | 'spo',
): Promise<CharacterOutput> {
  // Entities with fewer than 3 votes get the static fallback
  if (input.votePattern.total < 3) {
    return getEmergingVoiceCharacter(0);
  }

  try {
    const context = entityType === 'drep' ? 'drepCharacter' : 'spoCharacter';
    const systemPrompt = buildSenecaPrompt(context);
    const humanMessage = buildEntityDescription(input, entityType);

    const result = await generateJSON<CharacterOutput>(humanMessage, {
      model: 'FAST',
      maxTokens: 512,
      temperature: 0.7,
      system: systemPrompt,
    });

    // Validate the shape
    if (
      result &&
      typeof result.title === 'string' &&
      typeof result.summary === 'string' &&
      Array.isArray(result.pills) &&
      result.pills.length > 0
    ) {
      return {
        title: result.title,
        summary: result.summary,
        pills: result.pills.slice(0, 4).map((p) => ({
          label: typeof p.label === 'string' ? p.label : 'Unknown',
          reason: typeof p.reason === 'string' ? p.reason : '',
        })),
      };
    }

    logger.warn('[CharacterGen] Invalid JSON shape from AI, using fallback', {
      entityId: input.entityId,
    });
    return getEmergingVoiceCharacter(0);
  } catch (err) {
    logger.error('[CharacterGen] Generation failed', { error: err, entityId: input.entityId });
    return getEmergingVoiceCharacter(0);
  }
}
