#!/usr/bin/env bash
# Generate structural index for product registry staleness detection.
# Output: docs/strategy/context/registry/_index.generated.md
# Usage: bash scripts/generate-registry-index.sh [--check]
#   --check: Exit 1 if generated output differs from committed file (for preflight)

set -eo pipefail
cd "$(git rev-parse --show-toplevel)"

OUT="docs/strategy/context/registry/_index.generated.md"
TMP=$(mktemp)

cat > "$TMP" <<'HEADER'
# Structural Index (Auto-Generated)

> Generated by `scripts/generate-registry-index.sh`. Do NOT edit manually.
> Used for staleness detection — agents should read `product-registry.md` instead.

HEADER

# --- Routes ---
{
  echo "## Routes"
  echo ""
  find app -name "page.tsx" -type f | sed 's|/page\.tsx$||' | sed 's|^app||' | sort | sed 's|^|- `|;s|$|`|'
  echo ""
} >> "$TMP"

# --- Hooks ---
{
  echo "## Hooks"
  echo ""
  (ls hooks/use*.ts hooks/use*.tsx 2>/dev/null || true) | sed 's|hooks/||' | sort | sed 's|^|- `|;s|$|`|'
  echo ""
} >> "$TMP"

# --- Lib directories ---
{
  echo "## Lib Directories"
  echo ""
  for dir in lib/*/; do
    count=$(find "$dir" -maxdepth 1 \( -name "*.ts" -o -name "*.tsx" \) 2>/dev/null | wc -l | tr -d ' ')
    name=$(basename "$dir")
    echo "- \`${name}/\` (${count} files)"
  done
  echo ""
} >> "$TMP"

# --- Lib standalone files ---
{
  echo "## Lib Standalone Files"
  echo ""
  (ls lib/*.ts lib/*.tsx 2>/dev/null || true) | sed 's|lib/||' | sort | sed 's|^|- `|;s|$|`|'
  echo ""
} >> "$TMP"

# --- Governada components ---
{
  echo "## Components (governada/)"
  echo ""
  echo "### Directories"
  echo ""
  for dir in components/governada/*/; do
    [ -d "$dir" ] || continue
    count=$(find "$dir" -maxdepth 1 \( -name "*.tsx" -o -name "*.ts" \) 2>/dev/null | wc -l | tr -d ' ')
    name=$(basename "$dir")
    echo "- \`${name}/\` (${count} files)"
  done
  echo ""
  echo "### Files"
  echo ""
  (ls components/governada/*.tsx 2>/dev/null || true) | sed 's|components/governada/||' | sort | sed 's|^|- `|;s|$|`|'
  echo ""
} >> "$TMP"

# --- Inngest functions ---
{
  echo "## Inngest Functions"
  echo ""
  find inngest/functions -name "*.ts" -type f 2>/dev/null | sed 's|inngest/functions/||' | sort | sed 's|^|- `|;s|$|`|'
  echo ""
} >> "$TMP"

# --- Checksum + timestamp ---
CHECKSUM=$(sha256sum "$TMP" | cut -d' ' -f1)
{
  echo "---"
  echo "Checksum: \`${CHECKSUM}\`"
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} >> "$TMP"

if [[ "${1:-}" == "--check" ]]; then
  if [ -f "$OUT" ]; then
    # Compare content excluding the last 2 lines (checksum + timestamp)
    head -n -2 "$TMP" > "${TMP}.new"
    head -n -2 "$OUT" > "${TMP}.old"
    if ! diff -q "${TMP}.new" "${TMP}.old" > /dev/null 2>&1; then
      echo "WARNING: Registry index is stale. Run: bash scripts/generate-registry-index.sh"
      diff "${TMP}.old" "${TMP}.new" | head -20
      rm -f "$TMP" "${TMP}.new" "${TMP}.old"
      exit 1
    fi
    rm -f "${TMP}.new" "${TMP}.old"
  else
    echo "WARNING: Registry index does not exist. Run: bash scripts/generate-registry-index.sh"
    rm -f "$TMP"
    exit 1
  fi
  rm -f "$TMP"
  exit 0
fi

mv "$TMP" "$OUT"
ROUTE_COUNT=$(grep -c '^- ' "$OUT" || true)
echo "Registry index generated: $OUT ($ROUTE_COUNT entries)"
